### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by aleksandr-pavliuk** [aleksandr-pavliuk/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by alik-developer** [comment]
Donald John Trump Sr
Trump Tower
725 5th Avenue
New York, New York 10022
Work experience
Chairman and president, The Trump Organization, 1971–present:
“The Trump Organization is the world’s only global luxury real estate super-brand”
Oversees 22,000 employees
Responsible for Trump-branded residences, offices and hotels across US
Owns golf courses, battled with residents over opening of a course in Aberdeenshire, Scotland
Host, The Apprentice, The Celebrity Apprentice, 2004–present:
Hired and fired a number of business hopefuls
Believed some female contestants were after more than just a job: “All of the women on The Apprentice flirted with me — consciously or unconsciously. That’s to be expected.”
Chapter 11 bankruptcy filer, 1991–?:
Filed on four separate occasions: “I’ve used the laws of this country to pare debt. … We’ll have the company. We’ll throw it into a chapter. We’ll negotiate with the banks. We’ll make a fantastic deal. You know, it’s like on The Apprentice. It’s not personal. It’s just business.”
Writer, 1987–present:
Trump: The Art of the Deal
Trump: The Art of Survival
Trump: The Art of the Comeback
Trump: The Best Golf Advice I Ever Received
Owner, founder, Trump University, 2005–2010; Trump Entrepreneur Initiative founder, owner, 2010–present:
Said Trump University was “Ivy League-quality”; students disagreed: “Trump, as far as I can tell, had no real involvement in this program at all, other than collecting money, obviously. The thing’s a joke.”
New York attorney general brought lawsuit against Trump University in 2013. From the New York Times: “At one seminar, participants were told they would get to have their pictures taken with Mr Trump; it ended up being with a cardboard cutout.”
Changed name of “school” after New York Education Department said the use of the word “university” was “misleading” and “violates” state law
Founder, Trump Entertainment Resorts, 1995–2009:
Owned hotels and casinos including the Trump Taj Mahal in Atlantic City, which was under threat of closure in 2014. Trump Entertainment Resorts also owned the Trump Plaza casino, which closed in 2014.
Education
High school: New York Military Academy, class of 1964.
Fordham University: 1964–1966. Left because it was not challenging enough: “I decided that as long as I had to be in college, I might as well test myself against the best”.
Found the best at the University of Pennsylvania: The Wharton School. Graduated in 1968.
Secured a job straight out of college. At father’s company. Enjoyed a meteoric rise. Took control of the business in 1971.
Political experience
Thought about running for president in 1987, and in 2000, and in 2008, and in 2012

Thought about running for New York governor in 2013
Foreign policy
China, Japan and other countries are “ripping us off”. “We are being outfoxed by every country, every nation all over the world.” Would change this. “It’s about making America great again. I can do it, and nobody else can do it.”
Proposed taking over Iraq’s oil fields following the Iraq War, and using them to repay US military costs: “In the old days, you know when you had a war, to the victor belong the spoils.”
Potential obstacles
NBC executives are opposed: “They would love me not to run. Because I get a thing called ratings. And I have a very successful show.”
And again: “All of the people at NBC are working very, very hard on me. ‘Donald, we’ll give you anything. We’ll do anything you want to do. One year, two years, three years. Please, whatever you want to do.’”
Awards
Star on Hollywood Walk of Fame, 2007
Inducted into World Wrestling Entertainment Hall of Fame, 2013
