### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by aleksandr-pavliuk** [aleksandr-pavliuk/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by alik-developer** [comment]
Education
High school: New York Military Academy, class of 1964.
Fordham University: 1964–1966. Left because it was not challenging enough: “I decided that as long as I had to be in college, I might as well test myself against the best”.
Found the best at the University of Pennsylvania: The Wharton School. Graduated in 1968.
Secured a job straight out of college. At father’s company. Enjoyed a meteoric rise. Took control of the business in 1971.
Political experience
Thought about running for president in 1987, and in 2000, and in 2008, and in 2012

Thought about running for New York governor in 2013
Foreign policy
China, Japan and other countries are “ripping us off”. “We are being outfoxed by every country, every nation all over the world.” Would change this. “It’s about making America great again. I can do it, and nobody else can do it.”
Proposed taking over Iraq’s oil fields following the Iraq War, and using them to repay US military costs: “In the old days, you know when you had a war, to the victor belong the spoils.”
Potential obstacles
NBC executives are opposed: “They would love me not to run. Because I get a thing called ratings. And I have a very successful show.”
And again: “All of the people at NBC are working very, very hard on me. ‘Donald, we’ll give you anything. We’ll do anything you want to do. One year, two years, three years. Please, whatever you want to do.’”
Awards
Star on Hollywood Walk of Fame, 2007
Inducted into World Wrestling Entertainment Hall of Fame, 2013
